name: First Week of Release Rotation Checklist
description: Please see the full [release instructions](../../INSTRUCTIONS.md) for details.
title: "[Release vx.xx]: First Week of Rotation Checklist"
body:
- id: release-1
  type: checkboxes
  attributes:
    label: Which tasks have been fully completed?
    description: Please only check the boxes for tasks that are fully completed.
    options:
      - label: Prior release leads have been removed from rotation
      - label: New release leads have been added for the new rotation
      - label: A new Slack channel for the release has been created
      - label: A new GitHub issue for the "14 Days Prior to Release Checklist" has been created
