name: "1 Day Prior to Release Checklist"
description: Please see the full [release instructions](../../INSTRUCTIONS.md) for details.
title: "[Release vx.xx]: 1 Day Prior to Release Checklist"
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Which tasks have been fully completed?
    description: Please only check the boxes for tasks that are fully completed.
    options:
      - label: All items on the "7 Days Prior to Release Checklist" have been checked off
      - label: Readiness has been confirmed for each repo
      - label: Nighly builds have been checked for each repo
      - label: A new GitHub issue for the "Day of Release - First Batch of Repos Checklist" has been created