name: "Release - First Batch of Repos Checklist"
description: Please see the full [release instructions](../../INSTRUCTIONS.md) for details.
title: "[Release vx.xx]: First Batch of Repos Checklist"
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Which tasks have been fully completed? Please ensure there are no outstanding PRs for each repo release.
    description: Please only check the boxes for tasks that are fully completed. Please ensure there are no outstanding PRs for each repo release.
    options:
      - label: All items on the "1 Day Prior to Release Checklist" have been checked off
      - label: knative.dev/serving
      - label: knative.dev/net-certmanager
      - label: knative.dev/net-contour
      - label: knative.dev/net-http01
      - label: knative.dev/net-istio
      - label: knative.dev/net-kourier
      - label: knative.dev/net-gateway-api
      - label: knative.dev/eventing
      - label: knative.dev/sample-controller
      - label: A new GitHub issue for the "Release - Second Batch of Repos Checklist" has been created