name: "Release - Second Batch of Repos Checklist"
description: This is a release checklist for the repositories that depend on the `eventing` repo.
title: "[Release vx.xx]: Second Batch of Repos Checklist"
assignees:
  - carlisia
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please only mark each repo as done after it has been successfully released and published.
    description: The repos in this checklist can only be cut after the `eventing` repo has been [released and published](https://github.com/knative/eventing/releases). Please also ensure that there are no outstanding PRs for each repo before cutting its release branch. See the full [release instructions](https://github.com/knative/release/blob/0f481ee5e96a9bb9b515c4bc151e541d93bc05c7/INSTRUCTIONS.md) for details.
    options:
      - label: All items on the "Release - First Batch of Repos Checklist" have been checked off
        required: true
      - label: knative.dev/eventing-ceph
        required: true
      - label: knative.dev/eventing-kogito
        required: true
      - label: knative.dev/eventing-nats
        required: true
      - label: knative.dev/eventing-rabbitmq
        required: true
      - label: knative.dev/sample-source
        required: true
      - label: A new GitHub issue for the "Release - Third Batch of Repos Checklist" has been created
        required: true