name: "Release - Second Batch of Repos Checklist"
description: This release checklist requires that the eventing repo has been [released and published](https://github.com/knative/eventing/releases)..
title: "[Release vx.xx]: Second Batch of Repos Checklist"
assignees:
  - carlisia
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please only mark each repo as done after it has been verified as released and published.
    description: 1) Please change the title to include the current release. 2) Before cutting a release branch for any of the repos on this list, the `eventing` repo must have been [released and published](https://github.com/knative/eventing/releases). 3) Please ensure that there are no outstanding PRs for each repo before cutting its release branch. 4) See the full [release instructions](https://github.com/knative/release/blob/0f481ee5e96a9bb9b515c4bc151e541d93bc05c7/INSTRUCTIONS.md) for details. [test instructions](../../README.md)
    options:
      - label: All items on the "Release - First Batch of Repos Checklist" have been checked off
        required: true
      - label: knative.dev/eventing-ceph
      - label: knative.dev/eventing-kogito
      - label: knative.dev/eventing-nats
      - label: knative.dev/eventing-rabbitmq
      - label: knative.dev/sample-source
      - label: A new GitHub issue for the "Release - Third Batch of Repos Checklist" has been created
