name: "Release - Third Batch of Repos Checklist"
description: Please see the full [release instructions](../../INSTRUCTIONS.md) for details.
title: "[Release vx.xx]: Third Batch of Repos Checklist"
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Which tasks have been fully completed? Please ensure there are no outstanding PRs for each repo release.
    description: Please only check the boxes for tasks that are fully completed. Please ensure there are no outstanding PRs for each repo release.
    options:
      - label: All items on the "Release - Second Batch of Repos Checklist" have been checked off
      - label: knative.dev/client
      - label: knative.dev/eventing-kafka
      - label: knative.dev/eventing-redis
      - label: knative.dev/eventing-github
      - label: knative.dev/eventing-gitlab
      - label: A new GitHub issue for the "Release - Last Batch of Repos Checklist" has been created