name: "Release - Last Batch of Repos Checklist"
description: Please see the full [release instructions](../../INSTRUCTIONS.md) for details.
title: "[Release vx.xx]: Last Batch of Repos Checklist"
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Which tasks have been fully completed? Please ensure there are no outstanding PRs for each repo release.
    description: Please only check the boxes for tasks that are fully completed. Please ensure there are no outstanding PRs for each repo release.
    options:
      - label: All items on the "Release - Third Batch of Repos Checklist" have been checked off
      - label: knative.dev/eventing-kafka-broker
      - label: knative.dev/eventing-autoscaler-keda
      - label: knative.dev/kn-plugin-admin
      - label: knative.dev/kn-plugin-event
      - label: knative.dev/kn-plugin-source-kafka
      - label: knative.dev/kn-plugin-source-kamelet
      - label: knative.dev/kn-plugin-quickstart
      - label: A new GitHub issue for the "Release - Last Batch of Repos Checklist" has been created